# Generated by Django 4.2.7 on 2025-11-08 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='filled_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paper_trade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='paper_balance_usdt',
            field=models.DecimalField(decimal_places=8, default=10000, max_digits=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='paper_trading_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='PaperTradingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('average_buy_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paper trading positions',
                'unique_together': {('user', 'trading_pair')},
            },
        ),
    ]
