# Generated by Django 4.2.7 on 2025-11-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_order_filled_price_order_is_paper_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingstrategy',
            name='execution_interval',
            field=models.CharField(choices=[('15min', '15 Minutes'), ('30min', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], default='1h', max_length=10),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='next_execution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='stop_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='take_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='total_executions',
            field=models.IntegerField(default=0),
        ),
    ]
